### ISSUE TITLE
error running demo code

### ISSUE THREAD

**Issue by tsureshkumar** [hybridgroup/cylon-crazyflie#14]
I tried running the demo code against crazyflie 2.0.  I'm getting following error.

$ node test.js
I, [2015-07-04T20:32:28.351Z]  INFO -- : [Robot 1] - Starting connections.
STATE: setup --> connected
/opt/node-v0.12.6-linux-x64/lib/node_modules/cylon-crazyflie/node_modules/aerogel/lib/usbstreams.js:30
		this.endpoint.startStream(3, 64);
		              ^
TypeError: undefined is not a function
    at ReadableUSBStream._read (/opt/node-v0.12.6-linux-x64/lib/node_modules/cylon-crazyflie/node_modules/aerogel/lib/usbstreams.js:30:17)
    at ReadableUSBStream.Readable.read (_stream_readable.js:341:10)
    at _stream_readable.js:689:16
    at process._tickDomainCallback (node.js:381:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

My npm module versions are
┬ cylon-crazyflie@0.16.0
  ├─┬ aerogel@0.0.5
  │ ├─┬ leapjs@0.6.4
  │ │ ├── gl-matrix@2.2.1
  │ │ ├── underscore@1.4.4
  │ │ └─┬ ws@0.4.25
  │ │   ├── commander@0.6.1
  │ │   ├── options@0.0.6
  │ │   └── tinycolor@0.0.1
  │ ├── lodash@3.10.0
  │ ├─┬ optimist@0.6.1
  │ │ ├── minimist@0.0.10
  │ │ └── wordwrap@0.0.3
  │ ├── p-promise@0.5.0
  │ ├── state-machine@0.0.3
  │ └─┬ usb@1.0.6

Any idea?

**Comment by BClark-Grad-Project** [comment]
I'm not near a computer at the moment but I would guess its a node or package version issue. 
Brandon L. Clark
Graduate of CSU Fullerton | Software Engineering
P) 714.614.7951

Graduate Project:
http://themindspot.com | Questionnaire  Tools
http://api.themindspot.com | Questionnaire Developers

-----Original Message-----

**Comment by deadprogram** [comment]
We do not have one yet, so not much help. However, it appears that the protocol is mostly the same, so?

**Comment by dgellow** [comment]
Hello, I have the same error with a crazyflie v1.

**Comment by amfio** [comment]
I had this error too. Aerogels package.json doesn't specify dependency versions, which means it will always try and get the latest version. The problem appears to be that the "usb" library has changed at some point, breaking aerogel. I haven't experimented to find the most recent version of "usb" that works, but setting the version to 0.3.11 has worked for me.

**Comment by deadprogram** [comment]
Looks like it has been a long while since @ceejbot worked on aerogel actively, so @amfio perhaps you could submit a PR to Aerogel to lock the `usb` module to a specific version that you know works? Or if you have a fork, you could publish the fork and we could switch `cylon-crazyflie` to use it. Whatever is easiest for everyone.
