### ISSUE TITLE
Libusb errors running the demo code

### ISSUE THREAD

**Issue by beneichler** [hybridgroup/cylon-crazyflie#16]
Hi - 
Apologies if this isn't the right place for this but hopefully it is. 

I'm attempting to run the Crazyflie demo code and believe I have all the dependencies installed correctly; when I do, I get the following error: 

```
/node_modules/aerogel/node_modules/usb/usb.js:168
    this.device.__claimInterface(this.id)
                ^

Error: LIBUSB_ERROR_ACCESS
    at Error (native)
    at Interface.claim (/Users/etlab/Desktop/rise-of-the-machines/node_modules/aerogel/node_modules/usb/usb.js:168:14)
    at Crazyradio.setupRadio (/Users/etlab/Desktop/rise-of-the-machines/node_modules/aerogel/lib/crazyradio.js:111:17)
    at CrazyDriver.connect (/Users/etlab/Desktop/rise-of-the-machines/node_modules/aerogel/lib/crazydriver.js:136:20)
    at Copter.connect (/Users/etlab/Desktop/rise-of-the-machines/node_modules/aerogel/lib/copter.js:53:21)
    at Adaptor.doConnect (/Users/etlab/Desktop/rise-of-the-machines/node_modules/cylon-crazyflie/lib/adaptor.js:47:15)
    at Adaptor.connect (/Users/etlab/Desktop/rise-of-the-machines/node_modules/cylon-crazyflie/lib/adaptor.js:42:10)
    at Robot.startConnection (/Users/etlab/Desktop/rise-of-the-machines/node_modules/cylon/lib/robot.js:317:22)
    at Robot.<anonymous> (/Users/etlab/Desktop/rise-of-the-machines/node_modules/cylon/lib/robot.js:288:19)
    at /Users/etlab/Desktop/rise-of-the-machines/node_modules/cylon/lib/utils/helpers.js:237:36
```

which as far as I can tell has to do with the Node process' ability to access the radio dongle. Is this an issue with cylon-crazyflie, one of its dependencies, or none of the above? The Python client is able to read data from the dongle just fine, so it seems to be connecting to my Mac just fine. 

Any help anybody could provide here would be much appreciated - I'm totally unable to send commands to the copter for now.

Thanks!

**Comment by deadprogram** [comment]
Hi, @DangerZone14 

The issue is the `aerogel` module did not lock the dependency version on the `usb` module, and so is incompatible with the latest version: https://github.com/ceejbot/aerogel/blob/master/package.json#L22

Since that project is inactive, I would suggest forking `aerogel` to figure out the last version of `usb` that works, and then specify it. Hope that helps!

If you do create a fork of `aerogel` that works, please let us know.

**Comment by DangerZone14** [comment]
Thanks @deadprogram - I haven't been able to create a working fork yet but at least the problem is isolated now.

**Comment by rowellx68** [comment]
I have forked `aerogel` and updated it to work with the recent version of `node-usb`.

https://github.com/rowellx68/aerogel

And here's the modified `cylon-crazyflie` that will pull the modified `aerogel`

https://github.com/rowellx68/cylon-crazyflie

**Comment by deadprogram** [comment]
Hi, @rowellx68 would you be willing to submit a PR back to `cylon-crazyflie` with your changes?  It would be very appreciated!

**Comment by rowellx68** [comment]
@deadprogram pull request made, however, this version of `aerogel` is still prone to this issue: https://github.com/ceejbot/aerogel/issues/17
